'use client';

import { useMemo, useState } from 'react';
import './extra.css';

type Student={id:number;name:string;grade:string;className:string;sex:string;studentNo:string;phone:string;parentPhone:string;address:string;political:string;remark:string;status:string};
type RecordItem={id:number;name:string;className:string;status:string;detail:string;date:string};

const nav=[['概览','首页工作台'],['教务','课程与备课'],['学生','学生事务'],['请假','请假返校'],['团务','团务工作'],['导入','数据导入导出'],['设置','系统设置']];
const title:any={概览:'首页工作台',教务:'教务工作',学生:'学生信息与事务',请假:'请假与返校管理',团务:'团务工作',导入:'数据导入与资料库',设置:'系统设置'};
const seedStudents:Student[]=[
  {id:1,name:'张雨桐',grade:'九年级',className:'1班',sex:'女',studentNo:'2026001',phone:'13800001231',parentPhone:'张女士 13900001231',address:'海淀区知春路 88 号',political:'共青团员',remark:'学习适应情况需跟进',status:'需跟进'},
  {id:2,name:'王子轩',grade:'九年级',className:'1班',sex:'男',studentNo:'2026002',phone:'13800001232',parentPhone:'王先生 13900001232',address:'海淀区学院路 66 号',political:'群众',remark:'请假中，身体不适',status:'请假中'},
  {id:3,name:'林思琪',grade:'九年级',className:'3班',sex:'女',studentNo:'2026031',phone:'13800001233',parentPhone:'林女士 13900001233',address:'朝阳区望京街 16 号',political:'入团积极分子',remark:'培训材料齐全',status:'积极分子'},
  {id:4,name:'陈昊',grade:'九年级',className:'2班',sex:'男',studentNo:'2026018',phone:'13800001234',parentPhone:'陈先生 13900001234',address:'海淀区清河路 21 号',political:'共青团员',remark:'',status:'正常'},
];
const rows:Record<string,RecordItem[]>={教务:[{id:1,name:'思想道德与法治',className:'九年级 1班',status:'已授课',detail:'第三章 · 社会主义核心价值观',date:'08-24'},{id:2,name:'形势与政策',className:'九年级 2班',status:'待备课',detail:'专题二 · 青年使命担当',date:'08-26'}],请假:[{id:2,name:'王子轩',className:'九年级 1班',status:'请假中',detail:'身体不适，居家休养',date:'预计 08-26'},{id:5,name:'周雨欣',className:'九年级 3班',status:'请假中',detail:'事假，家长已说明',date:'预计 08-25'}],团务:[{id:3,name:'林思琪',className:'九年级 3班',status:'考察中',detail:'团的基础知识培训（已完成）',date:'08-18'}]};

export default function Home(){
 const[active,setActive]=useState('概览');const[students]=useState(seedStudents);const[query,setQuery]=useState('');const[searchOpen,setSearchOpen]=useState(false);const[student,setStudent]=useState<Student|null>(null);const[toast,setToast]=useState('');
 const say=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2600)};
 const allResults=useMemo(()=>[...students.map(s=>({...s,module:'学生',detail:s.remark})),...Object.entries(rows).flatMap(([module,list])=>list.map(x=>({...x,module})))].filter((x:any)=>(x.name+x.className+x.detail).includes(query)).slice(0,10),[students,query]);
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span>李</span><div><b>李老师工作台</b><small>个人教学管理</small></div></div><nav>{nav.map(([k,l])=><button key={k} className={active===k?'nav active':'nav'} onClick={()=>setActive(k)}><i>{k}</i>{l}</button>)}</nav><div className="profile"><span>李</span><div><b>李老师</b><small>教师账户</small></div></div></aside><section className="content"><header><button className="hamb">☰</button><div>工作台 <i>/</i> <b>{title[active]}</b></div><div className="head-right"><button onClick={()=>setSearchOpen(true)} aria-label="全局搜索">⌕</button><button>●<em>3</em></button><span>2026年8月24日 · 周一</span></div></header><div className="page">{active==='概览'?<Dashboard students={students} leaves={rows.请假} go={setActive}/>:active==='学生'?<Students students={students} onSelect={setStudent}/>:active==='导入'?<Files say={say}/>:active==='设置'?<Settings say={say}/>:<Records module={active} items={rows[active]||[]} say={say}/>}</div></section>{searchOpen&&<Search query={query} setQuery={setQuery} results={allResults} close={()=>setSearchOpen(false)} go={(m:string)=>{setActive(m);setSearchOpen(false)}} select={setStudent}/>} {student&&<StudentDetail student={student} close={()=>setStudent(null)}/>} {toast&&<div className="toast">✓　{toast}</div>}</main>
}

function Dashboard({students,leaves,go}:{students:Student[];leaves:RecordItem[];go:(s:string)=>void}){const[edit,setEdit]=useState(false);const[att,setAtt]=useState({expected:180,actual:180-leaves.length});return <><section className="welcome"><div><p>上午好，李老师</p><h1>今天，把重要的事安排清楚</h1><span>2026年秋季学期 · 第 1 周</span></div><button className="primary" onClick={()=>go('教务')}>＋ 新增备课</button></section><section className="stats"><Stat n="12" l="本学期备课" t="其中 8 条已授课"/><Stat n={String(leaves.length)} l="请假中学生" t="请在下方核对名单与原因" a/><Stat n="48" l="团员与积极分子" t="团员 39 人 · 积极分子 9 人"/><Stat n="6" l="待跟进事项" t="较昨日新增 2 项"/></section><section className="home-summary"><div className="card schedules"><Title label="今日资料" title="校历与课程表"/><div className="schedule-links"><button onClick={()=>go('导入')}><i>日</i><div><b>本学期校历</b><small>上传或查看教学周安排</small></div><span>→</span></button><button onClick={()=>go('导入')}><i>课</i><div><b>今日课程表</b><small>上传课程表，快速查看授课安排</small></div><span>→</span></button><button onClick={()=>go('导入')}><i>值</i><div><b>九年级值日表</b><small>上传班级值日安排</small></div><span>→</span></button></div></div><div className="card attendance"><div className="card-title"><div><small>每日出勤</small><h2>九年级到校情况</h2></div><button onClick={()=>setEdit(!edit)}>{edit?'完成':'编辑人数'}</button></div>{edit?<div className="attendance-edit"><label>应到<input type="number" value={att.expected} onChange={e=>setAtt({...att,expected:+e.target.value})}/></label><label>实到<input type="number" value={att.actual} onChange={e=>setAtt({...att,actual:+e.target.value})}/></label></div>:<div className="attendance-numbers"><div><b>{att.expected}</b><span>应到人数</span></div><div><b>{att.actual}</b><span>实到人数</span></div><div className="leave-total"><b>{Math.max(0,att.expected-att.actual)}</b><span>请假人数</span></div></div>}<div className="leave-roster"><div><b>请假名单与原因</b><button onClick={()=>go('请假')}>查看全部 →</button></div>{leaves.map(l=><div className="leave-row" key={l.id}><span>{l.name[0]}</span><div><b>{l.name} <small>{l.className}</small></b><p>{l.detail}</p></div><em>{l.date}</em></div>)}</div></div></section><section className="dash-grid"><div className="card reminder"><Title label="日程" title="今日提醒" btn="查看全部 →" onClick={()=>go('请假')}/><Event time="09:40" title="思想道德与法治" sub="九年级 1班 · 笃行楼 301" type="blue"/><Event time="返校" title="王子轩预计返校" sub="请假记录 · 请确认实际返校时间" type="red"/></div><div className="card quick"><Title label="快捷操作" title="快速开始"/><button onClick={()=>go('学生')}><i>人</i>学生档案与筛选 <span>→</span></button><button onClick={()=>go('请假')}><i>假</i>登记请假 <span>→</span></button><button onClick={()=>go('导入')}><i>⇅</i>导入 / 上传资料 <span>→</span></button></div></section></>}
function Students({students,onSelect}:{students:Student[];onSelect:(s:Student)=>void}){const[grade,setGrade]=useState('全部'),[cls,setCls]=useState('全部'),[sex,setSex]=useState('全部'),[q,setQ]=useState('');const list=students.filter(s=>(grade==='全部'||s.grade===grade)&&(cls==='全部'||s.className===cls)&&(sex==='全部'||s.sex===sex)&&(s.name+s.studentNo).includes(q));return <><section className="section-head"><div><p>按年级、班级和性别快速查询；点击姓名查看完整档案</p><h1>学生信息与事务</h1></div><button className="primary">＋ 新增学生</button></section><section className="filters card"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索姓名或学号…"/>{[['年级',grade,setGrade,['全部','九年级']],['班级',cls,setCls,['全部','1班','2班','3班']],['性别',sex,setSex,['全部','男','女']]].map(([label,value,set,opts]:any)=><label key={label}>{label}<select value={value} onChange={e=>set(e.target.value)}>{opts.map((x:string)=><option key={x}>{x}</option>)}</select></label>)}</section><section className="card table-card"><div className="table-title"><b>学生档案</b><small>共 {list.length} 人</small></div><div className="table-wrap"><table><thead><tr><th>姓名</th><th>年级班级</th><th>性别</th><th>政治面貌</th><th>状态</th><th>备注</th></tr></thead><tbody>{list.map(s=><tr key={s.id}><td><button className="name-link" onClick={()=>onSelect(s)}>{s.name}</button><small>{s.studentNo}</small></td><td>{s.grade} {s.className}</td><td>{s.sex}</td><td>{s.political}</td><td><span className="tag blue">{s.status}</span></td><td>{s.remark||'—'}</td></tr>)}</tbody></table></div></section></>}
function Records({module,items,say}:{module:string;items:RecordItem[];say:(x:string)=>void}){return <><section className="section-head"><div><p>{module==='教务'?'课程、备课与授课进度':module==='请假'?'请假名单、返校时间与原因':'团员、积极分子、培训与考核'}</p><h1>{title[module]}</h1></div><button className="primary" onClick={()=>say('新增表单已准备，请在下一版录入')}>＋ 新增记录</button></section><section className="card table-card"><div className="table-title"><b>全部记录</b><small>共 {items.length} 条</small></div><div className="table-wrap"><table><thead><tr><th>名称</th><th>班级</th><th>状态</th><th>内容 / 原因</th><th>时间</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><b>{i.name}</b></td><td>{i.className}</td><td><span className="tag blue">{i.status}</span></td><td>{i.detail}</td><td>{i.date}</td></tr>)}</tbody></table></div></section></>}
function Files({say}:{say:(x:string)=>void}){return <><section className="section-head"><div><p>上传校历、课程表和值日表，或导入 Excel 数据</p><h1>数据导入与资料库</h1></div></section><section className="imports">{['学生信息 Excel','请假返校 Excel','团务档案 Excel'].map(x=><div className="card import" key={x}><span>▤</span><h2>{x}</h2><p>支持 .xlsx、.xls、.csv 格式，导入前会校验姓名与班级字段。</p><div><button className="secondary" onClick={()=>say('模板下载已开始')}>下载模板</button><label className="primary">选择文件<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&say(`${e.target.files[0].name} 已选择，等待导入`)}/></label></div></div>)}</section><section className="card file-library"><Title label="文件存储" title="校历、课程表和值日表"/><p>资料上传后将显示在此处，并可在首页快速打开。</p><div className="file-actions">{['校历','课程表','值日表'].map(x=><label className="secondary" key={x}>＋ 上传{x}<input hidden type="file" onChange={e=>e.target.files?.[0]&&say(`${x} 已选择：${e.target.files[0].name}`)}/></label>)}</div></section></>}
function Settings({say}:{say:(x:string)=>void}){return <section className="card settings"><h2>系统设置</h2><label>显示名称<input defaultValue="李老师"/></label><button className="primary" onClick={()=>say('设置已保存')}>保存设置</button></section>}
function Search({query,setQuery,results,close,go,select}:any){return <div className="backdrop" onMouseDown={close}><div className="modal search-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-title"><div><small>全局搜索</small><h2>查找工作台记录</h2></div><button onClick={close}>×</button></div><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索学生、课程、请假原因或团务记录…"/>{results.map((r:any)=><button className="search-result" key={r.module+r.id} onClick={()=>{if(r.module==='学生')select(r);else go(r.module)}}><span>{title[r.module]}</span><div><b>{r.name}</b><small>{r.className} · {r.detail}</small></div></button>)}{query&&!results.length&&<p className="empty">没有找到匹配记录</p>}</div></div>}
function StudentDetail({student,close}:{student:Student;close:()=>void}){return <div className="backdrop" onMouseDown={close}><div className="modal student-detail" onMouseDown={e=>e.stopPropagation()}><div className="modal-title"><div><small>学生完整档案</small><h2>{student.name}</h2></div><button onClick={close}>×</button></div><div className="student-profile"><div className="student-photo">{student.name[0]}</div><div><b>{student.name}</b><p>{student.grade}{student.className} · {student.sex} · 学号 {student.studentNo}</p></div></div><div className="detail-grid"><Detail l="学生联系方式" v={student.phone}/><Detail l="家长联系方式" v={student.parentPhone}/><Detail l="家庭住址" v={student.address}/><Detail l="政治面貌" v={student.political}/><Detail l="状态" v={student.status}/><Detail l="备注" v={student.remark||'暂无'}/></div><div className="modal-actions"><button className="secondary" onClick={close}>关闭</button><button className="primary">编辑档案</button></div></div></div>}
function Detail({l,v}:{l:string;v:string}){return <div><small>{l}</small><b>{v}</b></div>};function Stat({n,l,t,a}:any){return <div className={'stat '+(a?'alert':'')}><small>{l}</small><b>{n}</b><p>{t}</p></div>};function Title({label,title:tt,btn,onClick}:any){return <div className="card-title"><div><small>{label}</small><h2>{tt}</h2></div>{btn&&<button onClick={onClick}>{btn}</button>}</div>};function Event({time,title,sub,type}:any){return <div className="event"><time>{time}</time><i className={type}/><div><b>{title}</b><small>{sub}</small></div><button>···</button></div>}
