import { index, integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

const timestamps = { createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() };
export const students = sqliteTable('students', { id: integer('id').primaryKey({ autoIncrement: true }), name: text('name').notNull(), studentNo: text('student_no'), className: text('class_name').notNull(), phone: text('phone'), parentPhone: text('parent_phone'), politicalStatus: text('political_status'), isMember: integer('is_member').notNull().default(0), isActivist: integer('is_activist').notNull().default(0), remark: text('remark'), ...timestamps }, t => [index('idx_students_class').on(t.className)]);
export const courses = sqliteTable('courses', { id: integer('id').primaryKey({ autoIncrement: true }), name: text('name').notNull(), semester: text('semester').notNull(), className: text('class_name').notNull(), totalHours: integer('total_hours').notNull(), progress: integer('progress').notNull().default(0), status: text('status').notNull(), ...timestamps });
export const lessonPlans = sqliteTable('lesson_plans', { id: integer('id').primaryKey({ autoIncrement: true }), courseId: integer('course_id').notNull(), className: text('class_name').notNull(), topic: text('topic').notNull(), hours: integer('hours').notNull(), objectives: text('objectives'), keyPoints: text('key_points'), process: text('process'), activities: text('activities'), homework: text('homework'), reflection: text('reflection'), status: text('status').notNull().default('草稿'), ...timestamps }, t => [index('idx_lesson_plans_course').on(t.courseId)]);
export const leaveRecords = sqliteTable('leave_records', { id: integer('id').primaryKey({ autoIncrement: true }), studentId: integer('student_id').notNull(), startAt: text('start_at').notNull(), expectedReturnAt: text('expected_return_at'), actualReturnAt: text('actual_return_at'), reason: text('reason'), status: text('status').notNull(), remark: text('remark'), ...timestamps }, t => [index('idx_leave_records_student_status').on(t.studentId, t.status)]);
export const youthMembers = sqliteTable('youth_members', { id: integer('id').primaryKey({ autoIncrement: true }), studentId: integer('student_id').notNull(), joinedAt: text('joined_at').notNull(), memberNo: text('member_no'), organization: text('organization'), status: text('status').notNull(), remark: text('remark'), ...timestamps }, t => [index('idx_youth_members_student').on(t.studentId)]);
export const activists = sqliteTable('activists', { id: integer('id').primaryKey({ autoIncrement: true }), studentId: integer('student_id').notNull(), appliedAt: text('applied_at'), stage: text('stage'), mentor: text('mentor'), status: text('status').notNull(), remark: text('remark'), ...timestamps }, t => [index('idx_activists_student').on(t.studentId)]);
export const trainingRecords = sqliteTable('training_records', { id: integer('id').primaryKey({ autoIncrement: true }), activistId: integer('activist_id').notNull(), topic: text('topic').notNull(), trainedAt: text('trained_at').notNull(), content: text('content'), attendance: text('attendance'), performance: text('performance'), completed: integer('completed').notNull().default(0), ...timestamps }, t => [index('idx_training_activist').on(t.activistId)]);
export const assessmentRecords = sqliteTable('assessment_records', { id: integer('id').primaryKey({ autoIncrement: true }), activistId: integer('activist_id').notNull(), assessedAt: text('assessed_at').notNull(), item: text('item'), result: text('result'), passed: integer('passed').notNull().default(0), opinion: text('opinion'), recorder: text('recorder'), ...timestamps }, t => [index('idx_assessment_activist').on(t.activistId)]);
